# Generated by Django 2.2.2 on 2019-10-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='card',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
