# Generated by Django 2.2.2 on 2019-12-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_person_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='alarm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='home',
            name='light',
            field=models.BooleanField(default=False),
        ),
    ]
